# Generated by Django 3.2.9 on 2021-12-04 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=20, verbose_name='email')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='password')),
                ('token', models.CharField(blank=True, max_length=20, null=True, verbose_name='token')),
            ],
            options={
                'db_table': 'auth',
            },
        ),
    ]
