# Generated by Django 3.2.9 on 2021-12-18 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myappsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('items', models.TextField(blank=True, null=True, verbose_name='items')),
            ],
            options={
                'db_table': 'list',
            },
        ),
    ]
