# Generated by Django 3.2.9 on 2021-12-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappsite', '0002_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='id',
            new_name='listId',
        ),
    ]
