# Generated by Django 3.2.9 on 2021-12-19 04:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myappsite', '0003_rename_id_list_listid'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日時'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='items')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myappsite.list', verbose_name='リスト')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
