# Generated by Django 3.2.9 on 2021-12-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappsite', '0004_auto_20211219_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='items',
        ),
    ]
