# Generated by Django 3.2.9 on 2021-12-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappsite', '0005_remove_list_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='list',
        ),
    ]
