# Generated by Django 3.2.9 on 2022-01-22 01:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myappsite', '0011_auto_20220122_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='listId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
